name: ai_smart_task_manager
description: An AI-powered smart task manager.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.11.0
  firebase_messaging: ^14.7.1
  http: ^0.15.0
  provider: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
